language: node_js

node_js:
  - "node"

instal:
  - npm install

script:
  - npm run test:coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # Send coverage data to Coveralls
